name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: |
        echo "Logging into Docker Hub..."
        echo "${{ secrets.DOCKERHUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        echo "Docker login successful!"

    # Build and push Docker image
    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-rest-server:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/chat-rest-server:latest .
        echo "Docker image built successfully. Pushing to Docker Hub..."
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-rest-server:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/chat-rest-server:latest
        echo "Docker image pushed successfully!"

    # Set up SSH key
    - name: Setup SSH key
      run: |
        echo "Setting up SSH key..."
        mkdir -p ~/.ssh
        echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > ~/.ssh/gcp_ecdsa_key
        chmod 600 ~/.ssh/gcp_ecdsa_key
        ssh-keyscan ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts
        echo "SSH key setup complete!"


    # Deploy on GCP VM
    - name: Deploy on GCP VM
      run: |
        echo "Deploying to GCP VM..."
        ssh -i ~/.ssh/gcp_ecdsa_key ${{ secrets.GCP_VM_USERNAME }}@${{ secrets.GCP_VM_IP }} << 'EOF'
        set -e  # Exit on error

        # Navigate to the chat-deploy folder and load the .env file
        echo "Navigating to chat-deploy directory..."
        cd chat-deploy/

        # Load environment variables from the .env file
        echo "Loading environment variables from .env file..."
        export $(cat .env | grep -v ^# | xargs)

        # Ensure MongoDB container is running
        echo "Ensuring MongoDB container is running..."
        sudo docker ps -q --filter "name=mongo" | grep -q . || sudo docker run -d --name mongo --network backend mongo
        echo "MongoDB container is running or started!"

        echo "Stopping and removing old chat-rest-server container if exists..."
        sudo docker ps -q --filter "name=chat-rest-server" | grep -q . && \
         sudo docker stop chat-rest-server && \
         sudo docker rm -f chat-rest-server && \
         sudo docker images -q ayushdixit23/chat-rest-server* | xargs sudo docker rmi -f && \
         echo "Old chat-rest-server container stopped and removed along with images."

        # Run new chat-rest-server container with env variables loaded from .env
        echo "Starting new chat-rest-server container..."
        sudo docker run -d \
          --name chat-rest-server \
          --restart always \
          --network chat-deploy_backend \
          -p $PORT_CHAT_REST:$PORT_CHAT_REST \
          -e PORT=$PORT_CHAT_REST \
          -e MONGO_URI=$MONGO_URI \
          -e NODE_ENV=$NODE_ENV \
          -e JWT_SECRET_KEY=$JWT_SECRET_KEY \
          -e AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
          -e AWS_SECRET_KEY=$AWS_SECRET_KEY \
          -e AWS_REGION=$AWS_REGION \
          -e BUCKET_NAME=$BUCKET_NAME \
          -e CLOUDFRONT_URL=$CLOUDFRONT_URL \
          -e AMPQ_URL=$AMPQ_URL \
          -e REDIS_URL=$REDIS_URL \
          ${{ secrets.DOCKERHUB_USERNAME }}/chat-rest-server:latest
        echo "New chat-rest-server container started successfully!"
        EOF
        echo "Deployment to GCP VM completed!"
